export const constants = ["null", "true", "false", "this", "super"];

export const primitiveTypes = [
  "int",
  "byte",
  "short",
  "long",
  "char",
  "double",
  "float",
  "boolean",

  "void",
  "never",

  "sequence",
  "array",
  "rlist",

  "nullable",
];

export const packages = ["java", "sand"];

export const javaDotLang = [
  "Appendable",
  "AutoCloseable",
  "CharSequence",
  "Cloneable",
  "Comparable",
  "Iterable",
  "Readable",
  "Runnable",
  "Boolean",
  "Byte",
  "Character",
  "Class",
  "ClassLoader",
  "ClassValue",
  "Compiler",
  "Double",
  "Enum",
  "Float",
  "InheritableThreadLocal",
  "Integer",
  "Long",
  "Math",
  "Number",
  "Object",
  "Package",
  "Process",
  "ProcessBuilder",
  "Runtime",
  "RuntimePermission",
  "SecurityManager",
  "Short",
  "StackTraceElement",
  "StrictMath",
  "String",
  "StringBuffer",
  "StringBuilder",
  "System",
  "Thread",
  "ThreadGroup",
  "ThreadLocal",
  "Throwable",
  "Void",
  "ArithmeticException",
  "ArrayIndexOutOfBoundsException",
  "ArrayStoreException",
  "ClassCastException",
  "ClassNotFoundException",
  "CloneNotSupportedException",
  "EnumConstantNotPresentException",
  "Exception",
  "IllegalAccessException",
  "IllegalArgumentException",
  "IllegalMonitorStateException",
  "IllegalStateException",
  "IllegalThreadStateException",
  "IndexOutOfBoundsException",
  "InstantiationException",
  "InterruptedException",
  "NegativeArraySizeException",
  "NoSuchFieldException",
  "NoSuchMethodException",
  "NullPointerException",
  "NumberFormatException",
  "ReflectiveOperationException",
  "RuntimeException",
  "SecurityException",
  "StringIndexOutOfBoundsException",
  "TypeNotPresentException",
  "UnsupportedOperationException",
  "AbstractMethodError",
  "AssertionError",
  "BootstrapMethodError",
  "ClassCircularityError",
  "ClassFormatError",
  "Error",
  "ExceptionInInitializerError",
  "IllegalAccessError",
  "IncompatibleClassChangeError",
  "InstantiationError",
  "InternalError",
  "LinkageError",
  "NoClassDefFoundError",
  "NoSuchFieldError",
  "NoSuchMethodError",
  "OutOfMemoryError",
  "StackOverflowError",
  "ThreadDeath",
  "UnknownError",
  "UnsatisfiedLinkError",
  "UnsupportedClassVersionError",
  "VerifyError",
  "VirtualMachineError",
];

export const all = [
  ...constants,
  ...primitiveTypes,
  ...packages,
  ...javaDotLang,
];
